### ISSUE TITLE
ADL2-core uses incompatible license

### ISSUE THREAD

**Issue by pieterbos** [openEHR/gdl-tools#10]
You linked to ADL2-core in a MPL/LGPL project. ADL2-core is released under a Affero GPL license. This means according to the Affero GPL license, that the GDL tools must also be released under the Affero GPL license or the GPL 3 license.

Since Affero GPL is quite restrictive for a library due to the above problem, you might not want to do this - or contact Marand to see if they are willing to license their project under a difference license, perhaps only for gdl-tools.

**Comment by icorbal** [comment]
For what I read, it's ok to use Affero GPL binaries as long as you don't change their source code. If you change it, then it's mandatory to publish it. We are not licensing the ADL2-core source code under MPL license, only the gdl-tools (that link to ADL2-core binaries).
https://softwareengineering.stackexchange.com/questions/107883/agpl-what-you-can-do-and-what-you-cant
My knowledge on licenses is quite limited, please let me know if this assumptions are wrong.

**Comment by pieterbos** [comment]
https://www.gnu.org/licenses/gpl-faq.en.html#GPLStaticVsDynamic

If you link Affero GPL code in your project, then distribute the project or host it online as a SaaS service, you must then release your own code as either GPLv3 of Affero GPL.

I guess if you contact Marand (copyright holder of adl2-core) they might give you permission to use their library in your project - then it's fine.
