### ISSUE TITLE
Not able to build 

### ISSUE THREAD

**Issue by bjornna** [openEHR/gdl-tools#3]
I am following the Install.txt and have run mvn install on the referenced projects. 
When trying to compile gdl-tools project I get the following error: 

[ERROR] Failed to execute goal on project openehr-utils-common: Could not resolve dependencies for project org.openehr.utils:openehr-utils-common:jar:0.95.6-SNAPSHOT: Could not find artifact openehr:openehr-rm-core:jar:1.0.11-SNAPSHOT -> [Help 1]

There must be some issues with references to correct library. 

/Bjørn

**Comment by icorbal** [comment]
The current gdl-tools project is pointing at an older version of the java libs (1.0.11-SNAPSHOT). If you have downloaded and installed the latest java-libs (https://github.com/openEHR/java-libs), you can update the value in the pom file. In gdl-tools/pom.xml change the value of openehr-java-libs-version from 1.0.11-SNAPSHOT to 1.0.14-SNAPSHOT. Hope it helps.
