### ISSUE TITLE
Java 1.8 is not supported

### ISSUE THREAD

**Issue by bjornna** [openEHR/gdl-tools#4]
The downloadable GDL Editor from http://sourceforge.net/projects/gdl-editor/ is not supporting Java 8. 

I have been able to compile the source. And the gdl-editor.exe will not run in Java 8. 

I am able to run the startup.bat|sh - so this is a workaround. 

It would be great for new users to be abel to run GDL Editor on the lates Java version.

**Comment by icorbal** [comment]
Yes, definitely. We have other requests for that. The problem with Java 8 is that it's not supported by drools 5.5, so an update to drools 6 is required. Sadly the new version is not backwards compatible, so there a a bunch of changes required. We have a first version that will be out soon (as soon as we test it properly).
