### ISSUE TITLE
Cannot read archetypes with UUID

### ISSUE THREAD

**Issue by danka74** [openEHR/gdl-tools#7]
The GDL Editor chokes on archetypes with UUIDs, e.g. the blood pressure archetype:

archetype (adl_version=1.4; uid=b1506a87-9bf2-4978-9eed-6ceecb0c2be9)
    openEHR-EHR-OBSERVATION.blood_pressure.v1

Error log:
INFO  se.cambio.openehr.controller.ArchetypeObjectBundleManager  - Parsing archetype 'openEHR-EHR-OBSERVATION.glasgow_coma_scale.v1'...
WARN  se.cambio.openehr.util.ExceptionHandler  - org.openehr.rm.support.identification.UUID
java.io.NotSerializableException: org.openehr.rm.support.identification.UUID

**Comment by rongchen** [comment]
It's a known issue, which likely needs a fix on the parser. For now, just remove the UUID from the file.

**Comment by danka74** [comment]
Yes, that's what we did. Thanks, Daniel

Sent by MailWise<http://www.mail-wise.com/installation/4> – Your emails, with style.:)


-------- Ursprungligt meddelande --------
Ämne: Re: [openEHR/gdl-tools] Cannot read archetypes with UUID (#7)
Från: Rong Chen <notifications@github.com>
Till: openEHR/gdl-tools <gdl-tools@noreply.github.com>
Kopia: Daniel Karlsson <daniel.karlsson@liu.se>,Author <author@noreply.github.com>


It's a known issue, which likely needs a fix on the parser. For now, just remove the UUID from the file.
