### ISSUE TITLE
About connect  to the database 

### ISSUE THREAD

**Issue by YehShihHao** [openEHR/gdl-tools#8]
Hi 
I am a graduate student in Taiwan.
My research topic is to use openEHR to construct a CDSS for hospital 
GDL-tools has been successfully established.
I try to modify the code of GDL-Tools 
But now I can not  connect the system to the database
someone have any solution?
Or there are other tools to help gdl editor with the database connection
Thank you very much ~

**Comment by bjornna** [comment]
Hi 
I am not sure what you are trying to do. We have used the GDL tools only as an editor for GDL files. I was not aware of any features to connect the tool to a database. 

We have implemented an openEHR server where you can import GDL files (created with GDL tools) and then execute them on an EHR. The API is like this: 

_GET /api/v1/cds/{ehrId}/{guideId}_ 

Is this what you are trying to do? 

Best regards 
Bjørn Næss, Product owner DIPS ASA

**Comment by YehShihHao** [comment]
Thank you very much for your reply!!
Will you say that the openEHR server is EHRScape?
Still have other servers?
EHRScape did not see the open source on the Internet.
My research hopes to bring OpenEHR to hospitals in Taiwan.
I would like to use the openEHR framework to make a CDSS prototype to do with the hospital database connection.
How can I use your "openEHR server"?

Regards,
Kira Yeh

**Comment by bjornna** [comment]
Our server is not EhrScape.  That is a great product by Marand . We have implemented a similar product which is compatible with EhrScape.  Actually we use both in a testing environment.  
Our, Arena Ehr Server, is not open source. But we are available in the market as any other of these products.
