### ISSUE TITLE
V0.94 Import Templates have error message

### ISSUE THREAD

**Issue by YehShihHao** [openEHR/gdl-tools#9]
Hi! There,
I found that when I import the template into 0.94 version of the GDL-Editor, 
it will cause the error message. "An error has been found while parsing the template"
But if I download  the 0.95.6 version, the program can be normally built.
So, I'm wondering where can I found the source code of  V0.956 GDL-Editor?

**Comment by icorbal** [comment]
Latest version (master) is a SNAPSHOT of 0.95.6.
We'll be soon releasing a major update (1.2).

**Comment by YehShihHao** [comment]
The GDL-tools lastest verson (master) is a SNAPSHOT of 0.95.6.
What is the version of the other two programs?

Such as build V0.94 GDL-tools need
Adl2-core => 1.0.0
Java-lib => 1.0.10
How about build (master) 0.95.6 verson?

**Comment by YehShihHao** [comment]
If I want build GDL-Editor of version (master)
adl2-core and Java-lib 
Which tag should I choose?

I lookup git tag, can build success v0.94 Gdl-tool, but I want to build v0.95.6
then I checkout "3aa1ef691ad6aec20f814dfc38ee796c2bd1dfd7 [maven-release-plugin] prepare release gdl-tools-0.95.6" can't build.

I tried to use the tag of master version but failed
adl2-core   Mast
java-libs   Mast
gdl-tools   Mast
MVN result OpenEHR utils common ............................... FAILURE [  0.057 s]

Can you tell me which commit id ??
